version: "3.8"

services:
  scraper:
    build: .
    container_name: property_scraper
    restart: always
    volumes:
      - ./logs:/var/log
    environment:
      - FIREBASE_PROJECT_ID=your_project_id
      - FIREBASE_CLIENT_EMAIL=your_client_email
      - FIREBASE_PRIVATE_KEY=your_private_key
